package com.nexos.backend.api.exception;

public enum MessageCode {
	
	ERROR_SISTEMA("000"),
	USER_NOT_FOUND_OR_INVALID_PASSWORD("001"),
	FIND_ALL_ADDRESS_ERROR("002"), FIND_ADDRESS_ERROR("003"), DELETE_ADDRESS_ERROR("004"), 
	FIND_ALL_CITY_ERROR("005"), FIND_CITY_ERROR("006"), DELETE_CITY_ERROR("007"), 
	FIND_ALL_CLIENT_ERROR("008"), FIND_CLIENT_ERROR("009"), DELETE_CLIENT_ERROR("010"), 
	FIND_ALL_COMBO_ERROR("011"), FIND_COMBO_ERROR("012"), DELETE_COMBO_ERROR("013"), 
	FIND_ALL_COMBOSERVICE_ERROR("014"), FIND_COMBOSERVICE_ERROR("015"), DELETE_COMBOSERVICE_ERROR("016"), 
	FIND_ALL_CONTACT_ERROR("017"), FIND_CONTACT_ERROR("018"), DELETE_CONTACT_ERROR("019"), 
	FIND_ALL_CONTACTTYPE_ERROR("020"), FIND_CONTACTTYPE_ERROR("021"), DELETE_CONTACTTYPE_ERROR("022"), 
	FIND_ALL_COUNTRY_ERROR("023"), FIND_COUNTRY_ERROR("024"), DELETE_COUNTRY_ERROR("025"), 
	FIND_ALL_DEPARTMENT_ERROR("026"), FIND_DEPARTMENT_ERROR("027"), DELETE_DEPARTMENT_ERROR("028"), 
	FIND_ALL_DISCOUNT_ERROR("029"), FIND_DISCOUNT_ERROR("030"), DELETE_DISCOUNT_ERROR("031"), 
	FIND_ALL_DOCUMENTTYPE_ERROR("031"), FIND_DOCUMENTTYPE_ERROR("032"), DELETE_DOCUMENTTYPE_ERROR("033"), 
	FIND_ALL_ITEM_ERROR("034"), FIND_ITEM_ERROR("035"), DELETE_ITEM_ERROR("036"), 
	FIND_ALL_MENU_ERROR("037"), FIND_MENU_ERROR("038"), DELETE_MENU_ERROR("039"), 
	FIND_ALL_PERSON_ERROR("040"), FIND_PERSON_ERROR("041"), DELETE_PERSON_ERROR("042"), 
	FIND_ALL_PERSONTYPE_ERROR("043"), FIND_PERSONTYPE_ERROR("044"), DELETE_PERSONTYPE_ERROR("045"), 
	FIND_ALL_QUOTATIONCOMBO_ERROR("046"), FIND_QUOTATIONCOMBO_ERROR("047"), DELETE_QUOTATIONCOMBO_ERROR("048"), 
	FIND_ALL_REFERENCE_ERROR("049"), FIND_REFERENCE_ERROR("050"), DELETE_REFERENCE_ERROR("051"), 
	FIND_ALL_ROL_ERROR("052"), FIND_ROL_ERROR("053"), DELETE_ROL_ERROR("054"), 
	FIND_ALL_SERVICE_ERROR("055"), FIND_SERVICE_ERROR("056"), DELETE_SERVICE_ERROR("057"), 
	FIND_ALL_SERVICETYPE_ERROR("058"), FIND_SERVICETYPE_ERROR("059"), DELETE_SERVICETYPE_ERROR("060"), 
	CREATE_ADDRESS_ERROR("061"), CREATE_CLIENT_ERROR("062"), CREATE_CITY_ERROR("063"), CREATE_COMBO_ERROR("064"), 
	CREATE_COMBOSERVICE_ERROR("065"), CREATE_CONTACT_ERROR("066"), CREATE_CONTACTTYPE_ERROR("067"), 
	CREATE_COUNTRY_ERROR("068"), CREATE_DEPARTMENT_ERROR("069"), CREATE_DISCOUNT_ERROR("070"), 
	CREATE_DOCUMENTTYPE_ERROR("071"), CREATE_ITEM_ERROR("072"), CREATE_MENU_ERROR("073"), CREATE_PERSON_ERROR("074"), 
	CREATE_PERSONTYPE_ERROR("075"), CREATE_QUOTATIONCOMBO_ERROR("076"), 
	FIND_ALL_QUOTATION_ERROR("077"), FIND_QUOTATION_ERROR("078"), DELETE_QUOTATION_ERROR("079"), CREATE_QUOTATION_ERROR("080"),
	CREATE_ROL_ERROR("081"), CREATE_SERVICE_ERROR("082"), CREATE_SERVICETYPE_ERROR("083"), USER_NOT_FOUND("084"), 
	RECOVERY_PASSWORD_MESSAGE("085"), FIND_ALL_USER_ERROR("086"), FIND_USER_ERROR("087"), DELETE_USER_ERROR("088"), 
	CREATE_USER_ERROR("089");
	
	
	String code;
	MessageCode(String code){
		this.code = code;
	}
}
